apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testdummies.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: TestDummy
    plural: testdummies
    singular: testdummy
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
