apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functiontests.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: FunctionTest
    plural: functiontestss
    singular: functiontest
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                functionRef:
                  type: object
                  nullable: false
                  properties:
                    name:
                      type: string
                      nullable: false
                  required: [name]

                parent:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: true

                inputs:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: true

                currentResource:
                  type: object
                  nullable: true
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true

                expectedResource:
                  type: object
                  nullable: true
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true

                expectedOkValue:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: true

                expectedOutcome:
                  type: object
                  x-kubernetes-validations:
                    - rule: (self.type == 'Retry' && has(self.delay) && self.delay > 0) || self.type != 'Retry'
                      message: "Retry validators must provide delay-seconds."
                    - rule: (self.type != 'Retry' && !has(self.delay)) || self.type == 'Retry'
                      message: "Non-retry validators must not provide delay-seconds."
                    - rule: (self.type == 'Ok' && !has(self.message)) || self.type != 'Ok'
                      message: "Ok validators should not provide a message."

                  properties:
                    type:
                      type: string
                      nullable: false
                      enum: [Ok, PermFail, Retry]
                    message:
                      type: string
                      nullable: true
                    delay:
                      type: integer
                      nullable: true
                  required: [type]

            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
