apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functiontests.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: FunctionTest
    plural: functiontestss
    singular: functiontest
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                functionRef:
                  type: object
                  nullable: false
                  properties:
                    name:
                      type: string
                      nullable: false
                  required: [name]

                parent:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: true

                inputs:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: true

                expectedResource:
                  type: object
                  nullable: true
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true

            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
