apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functiontests.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: FunctionTest
    plural: functiontests
    singular: functiontest
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: [spec]
          properties:
            spec:
              type: object
              nullable: false
              properties:
                functionRef:
                  type: object
                  nullable: false
                  properties:
                    kind:
                      type: string
                      nullable: false
                      enum: [ResourceFunction, ValueFunction]
                    name:
                      type: string
                      nullable: false
                  required: [kind, name]

                inputs:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: false

                currentResource:
                  type: object
                  nullable: false
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true

                testCases:
                  type: array
                  nullable: false
                  maxItems: 10
                  items:
                    type: object
                    properties:
                      label:
                        type: string
                        nullable: false

                      variant:
                        type: boolean
                        nullable: false

                      skip:
                        type: boolean
                        nullable: false
                        default: false

                      inputOverrides:
                        type: object
                        nullable: false
                        x-kubernetes-preserve-unknown-fields: true

                      currentResource:
                        type: object
                        nullable: false
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true

                      overlayResource:
                        type: object
                        nullable: false
                        x-kubernetes-preserve-unknown-fields: true

                      expectResource:
                        type: object
                        nullable: false
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true

                      expectDelete:
                        type: boolean
                        nullable: false

                      expectReturn:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        nullable: false

                      expectOutcome:
                        type: object
                        properties:
                          ok:
                            type: object
                            nullable: true
                          skip:
                            type: object
                            nullable: false
                            properties:
                              message:
                                type: string
                                nullable: false
                            required: [message]
                          depSkip:
                            type: object
                            nullable: false
                            properties:
                              message:
                                type: string
                                nullable: false
                            required: [message]
                          retry:
                            type: object
                            nullable: false
                            properties:
                              message:
                                type: string
                                nullable: false
                              delay:
                                type: integer
                                nullable: false
                            required: [message, delay]
                          permFail:
                            type: object
                            nullable: false
                            properties:
                              message:
                                type: string
                                nullable: false
                            required: [message]
                        oneOf:
                          - required: [ok]
                          - required: [skip]
                          - required: [depSkip]
                          - required: [retry]
                          - required: [permFail]

                expectResource:
                  type: object
                  nullable: false
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true

                expectReturn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: false

                expectOutcome:
                  type: object
                  properties:
                    ok:
                      type: object
                      nullable: true
                    skip:
                      type: object
                      nullable: false
                      properties:
                        message:
                          type: string
                          nullable: false
                      required: [message]
                    depSkip:
                      type: object
                      nullable: false
                      properties:
                        message:
                          type: string
                          nullable: false
                      required: [message]
                    retry:
                      type: object
                      nullable: false
                      properties:
                        message:
                          type: string
                          nullable: false
                        delay:
                          type: integer
                          nullable: false
                      required: [message, delay]
                    permFail:
                      type: object
                      nullable: false
                      properties:
                        message:
                          type: string
                          nullable: false
                      required: [message]
                  required: [assert]
                  oneOf:
                    - required: [ok]
                    - required: [skip]
                    - required: [depSkip]
                    - required: [retry]
                    - required: [permFail]

            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
