apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functiontests.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: FunctionTest
    plural: functiontests
    singular: functiontest
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                functionRef:
                  type: object
                  nullable: false
                  properties:
                    name:
                      type: string
                      nullable: false
                  required: [name]

                inputs:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: true

                currentResource:
                  type: object
                  nullable: true
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true

                expectedResource:
                  type: object
                  nullable: true
                  x-kubernetes-embedded-resource: true
                  x-kubernetes-preserve-unknown-fields: true

                expectedReturn:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  nullable: true

                expectedOutcome:
                  type: object
                  properties:
                    ok:
                      type: object
                      nullable: true
                    skip:
                      type: object
                      nullable: true
                      properties:
                        message:
                          type: string
                          nullable: false
                      required: [message]
                    depSkip:
                      type: object
                      nullable: true
                      properties:
                        message:
                          type: string
                          nullable: false
                      required: [message]
                    retry:
                      type: object
                      nullable: true
                      properties:
                        message:
                          type: string
                          nullable: false
                        delay:
                          type: integer
                          nullable: false
                      required: [message, delay]
                    permFail:
                      type: object
                      nullable: true
                      properties:
                        message:
                          type: string
                          nullable: false
                      required: [message]
                  required: [assert]
                  oneOf:
                    - properties:
                      required: [ok]
                    - properties:
                      required: [skip]
                    - properties:
                      required: [depSkip]
                    - properties:
                      required: [retry]
                    - properties:
                      required: [permFail]

            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
