apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functions.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: Function
    plural: functions
    singular: function
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                staticResource:
                  nullable: true
                  type: object
                  properties:
                    behavior:
                      type: object
                      nullable: false
                      properties:
                        load:
                          type: string
                          enum: [name, query, virtual]
                          default: name
                          nullable: false

                        create:
                          type: boolean
                          default: true
                          nullable: false

                        update:
                          type: string
                          enum: [patch, recreate, never]
                          default: patch
                          nullable: false

                        delete:
                          type: string
                          enum: [destroy, abandon]
                          default: destroy
                          nullable: false
                    managedResource:
                      type: object
                      nullable: true
                      properties:
                        apiVersion:
                          type: string
                          nullable: false
                        kind:
                          type: string
                          nullable: false
                        plural:
                          type: string
                          nullable: true
                        namespaced:
                          type: boolean
                          default: true
                          nullable: false
                dynamicResource:
                  nullable: true
                  type: object
                  properties:
                    key:
                      type: string
                      nullable: false
                inputValidators:
                  nullable: true
                  type: array
                  maxItems: 20
                  items:
                    type: object
                    properties:
                      assert:
                        type: string
                        nullable: false
                        x-kubernetes-validations:
                          - rule: self.startsWith('=')
                            message: "assertion must be a cel expression (start with '=')."
                      ok:
                        type: object
                        nullable: true
                      skip:
                        type: object
                        nullable: true
                        properties:
                          message:
                            type: string
                            nullable: false
                        required: [message]
                      depSkip:
                        type: object
                        nullable: true
                        properties:
                          message:
                            type: string
                            nullable: false
                        required: [message]
                      retry:
                        type: object
                        nullable: true
                        properties:
                          message:
                            type: string
                            nullable: false
                          delay:
                            type: integer
                            nullable: false
                        required: [message, delay]
                      permFail:
                        type: object
                        nullable: true
                        properties:
                          message:
                            type: string
                            nullable: false
                        required: [message]
                    required: [assert]
                    oneOf:
                      - properties:
                        required: [ok]
                      - properties:
                        required: [skip]
                      - properties:
                        required: [depSkip]
                      - properties:
                        required: [retry]
                      - properties:
                        required: [permFail]
                outcome:
                  nullable: true
                  type: object
                  properties:
                    validators:
                      nullable: true
                      type: array
                      maxItems: 20
                      items:
                        type: object
                        properties:
                          assert:
                            type: string
                            nullable: false
                            x-kubernetes-validations:
                              - rule: self.startsWith('=')
                                message: "assertion must be a cel expression (start with '=')."
                          ok:
                            type: object
                            nullable: true
                          skip:
                            type: object
                            nullable: true
                            properties:
                              message:
                                type: string
                                nullable: false
                            required: [message]
                          depSkip:
                            type: object
                            nullable: true
                            properties:
                              message:
                                type: string
                                nullable: false
                            required: [message]
                          retry:
                            type: object
                            nullable: true
                            properties:
                              message:
                                type: string
                                nullable: false
                              delay:
                                type: integer
                                nullable: false
                            required: [message, delay]
                          permFail:
                            type: object
                            nullable: true
                            properties:
                              message:
                                type: string
                                nullable: false
                            required: [message]
                        required: [assert]
                        oneOf:
                          - properties:
                            required: [ok]
                          - properties:
                            required: [skip]
                          - properties:
                            required: [depSkip]
                          - properties:
                            required: [retry]
                          - properties:
                            required: [permFail]
                    return:
                      nullable: true
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                materializers:
                  nullable: true
                  type: object
                  properties:
                    base:
                      nullable: true
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    onCreate:
                      nullable: true
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
