apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: functions.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: Function
    plural: functions
    singular: function
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                managedResource:
                  type: object
                  nullable: false
                  properties:
                    crd:
                      type: object
                      nullable: true
                      properties:
                        apiVersion:
                          type: string
                          nullable: false
                        kind:
                          type: string
                          nullable: false
                        plural:
                          type: string
                          nullable: true
                        namespaced:
                          type: boolean
                          default: true
                          nullable: false

                    behaviors:
                      type: object
                      nullable: false
                      properties:
                        virtual:
                          type: boolean
                          default: false
                          nullable: false

                        load:
                          type: string
                          enum: [name, query]
                          default: name
                          nullable: false

                        update:
                          type: string
                          enum: [patch, recreate]
                          default: patch
                          nullable: false

                        delete:
                          type: string
                          enum: [destroy, abandon]
                          default: destroy
                          nullable: false

                inputValidators:
                  nullable: true
                  type: array
                  items:
                    type: object
                    x-kubernetes-validations:
                      - rule: (self.type == 'Retry' && has(self.delay) && self.delay > 0) || self.type != 'Retry'
                        message: "Retry validators must provide delay-seconds."
                      - rule: (self.type != 'Retry' && !has(self.delay)) || self.type == 'Retry'
                        message: "Non-retry validators must not provide delay-seconds."

                    properties:
                      type:
                        type: string
                        nullable: false
                        enum: [DepSkip, Ok, PermFail, Retry, Skip]
                      test:
                        type: string
                        nullable: false
                      message:
                        type: string
                        nullable: false
                      delay:
                        type: integer
                        nullable: true
                    required: [type, test, message]

                outcome:
                  nullable: true
                  type: object
                  properties:
                    tests:
                      nullable: true
                      type: array
                      items:
                        type: object
                        x-kubernetes-validations:
                          - rule: (self.type == 'Retry' && has(self.delay) && self.delay > 0) || self.type != 'Retry'
                            message: "Retry validators must provide delay-seconds."
                          - rule: (self.type != 'Retry' && !has(self.delay)) || self.type == 'Retry'
                            message: "Non-retry validators must not provide delay-seconds."
                          - rule: (self.type == 'Ok' && !has(self.message)) || self.type != 'Ok'
                            message: "Ok validators should not provide a message."

                        properties:
                          type:
                            type: string
                            nullable: false
                            enum: [Ok, PermFail, Retry]
                          test:
                            type: string
                            nullable: false
                          message:
                            type: string
                            nullable: true
                          delay:
                            type: integer
                            nullable: true
                        required: [type, test]

                    okValue:
                      nullable: true
                      type: string

                materializers:
                  nullable: true
                  type: object
                  properties:
                    base:
                      nullable: true
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    onCreate:
                      nullable: true
                      type: object
                      x-kubernetes-preserve-unknown-fields: true

                template:
                  nullable: true
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  x-kubernetes-embedded-resource: true

            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
