apiVersion: v1
kind: Namespace
metadata:
  name: koreo-testing
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: empty.v1
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/bump: "13"
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: input-validation-tests.v1
  namespace: koreo-testing
spec:
  inputValidators:
    - type: Skip
      message: number too small, must be over 5.
      test: =inputs.number < 5

    - type: PermFail
      message: optional number not equal to 3333.
      test: =has(inputs.optional_number) && inputs.optional_number != 3333

    - type: Retry
      message: number too large, must be under 13.
      test: =inputs.number > 13
      delay: 90

    - type: PermFail
      message: number too small, must be over 1.
      test: =inputs.number < 1

    - type: Retry
      message: optional retry_number not equal to 1212.
      test: =has(inputs.optional_retry_number) && inputs.optional_retry_number != 1212
      delay: 75

    - type: Skip
      message: ="value for message (\"" + inputs.value_for_message + "\") was set."
      test: =has(inputs.value_for_message)
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: outcome-tests.v1
  namespace: koreo-testing
spec:
  outcome:
    tests:
      - type: Retry
        message: number too large, must be under 13.
        test: =inputs.number > 13
        delay: 90

      - type: PermFail
        message: optional number not equal to 3333.
        test: =has(inputs.optional_number) && inputs.optional_number != 3333

      - type: Ok
        test: =has(inputs.output) && inputs.output == 11221122
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: outcome-ok-value.v1
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/bump: "4"
spec:
  outcome:
    okValue: "=has(inputs.output) ? inputs.output: null"
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: materializers-base-nested.v1
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/bump: "12"
spec:
  materializers:
    base:
      apiVersion: tests.koreo.realkinetic.com/v1alpha8
      kind: TestCase
      metadata:
        name: base-test
        namespace: =inputs.metadata.namespace
      spec:
        name: =inputs.person.name
        age: =inputs.person.age
        children.*:
          name: =inputs.person.name + ', Jr.'
          age: =inputs.person.age - 20
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: materializers-base-flat.v1
  namespace: koreo-testing
spec:
  materializers:
    base:
      "apiVersion": tests.koreo.realkinetic.com/v1alpha8
      "kind": TestCase
      "metadata.name": base-test
      "metadata.namespace": =inputs.metadata.namespace
      "spec.name": =inputs.person.name
      "spec.age": =inputs.person.age
      "spec.children.*":
        {
          "name": '=inputs.person.name + ", Jr."',
          "age": "=inputs.person.age - 20",
        }
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: materializers-on-create-nested.v1
  namespace: koreo-testing
spec:
  materializers:
    base:
      apiVersion: tests.koreo.realkinetic.com/v1alpha8
      kind: TestCase
      metadata:
        name: base-test
      spec:
        name: Name of Person
        age: Age of Person
        children:
          - name: Name of Child
            age: Age of Child
    onCreate:
      metadata:
        namespace: =inputs.metadata.namespace
      spec:
        name: =inputs.person.name
        age: =inputs.person.age
        children.*: |
          ={ "name": inputs.person.name + ", Jr.", "age": inputs.person.age - 20 }
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: materializers-on-create-flat.v1
  namespace: koreo-testing
spec:
  materializers:
    base:
      apiVersion: tests.koreo.realkinetic.com/v1alpha8
      kind: TestCase
      metadata:
        name: base-test
      spec:
        name: Name of Person
        age: Age of Person
        children:
          - name: Name of Child
            age: Age of Child
    onCreate:
      "metadata.namespace": =inputs.metadata.namespace
      "spec.name": =inputs.person.name
      "spec.age": =inputs.person.age
      "spec.children.*": |
        ={ "name": inputs.person.name + ", Jr.", "age": inputs.person.age - 20 }
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: gcp-folder.v1
  namespace: koreo-testing
spec:
  outcome:
    tests:
      - type: Ok
        test: =resource.config_connect_ready()

    okValue: |
      ={"folderId": resource.status.folderId, "ref": resource.self_ref() }

  materializers:
    base:
      apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
      kind: Folder
      metadata: =inputs.metadata
      spec:
        displayName: =inputs.params.name
        folderRef: =inputs.parent_folder.ref.to_ref()
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: dummy-test.v1
  namespace: koreo-testing
spec:
  managedResource:
    apiVersion: koreo.realkinetic.com/v1alpha8
    kind: TestDummy
    plural: testdummies
    namespaced: true

  behavior:
    update: recreate

  materializers:
    base:
      apiVersion: koreo.realkinetic.com/v1alpha8
      kind: TestDummy
      metadata:
        name: =parent.metadata.name
        namespace: =string("koreo-testing")
        labels:
          testing.realkinetic.com/key: =parent.metadata.name
      spec:
        intKey: 99
        strKey: =string("A string!")
        listKey:
          - name: first
            value: 1
          - name: second
            value: 2
        mapKey:
          name: some
          value: 10

  outcome:
    okValue: =resource.metadata.uid
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: domain-config.v1
  namespace: koreo-testing
spec:
  behavior:
    load: virtual
    create: false
    update: never
    delete: abandon

  inputValidators:
    - type: PermFail
      message: Domain resource-name must start with a letter.
      test: =parent.metadata.name.matches("^[0-9][a-zA-Z]+")

    - type: PermFail
      message: Domain resource must have platform label.
      test: '=!has(parent.metadata.labels["konfig.realkinetic.com/platform"])'

  outcome:
    okValue: |
      ={
        "domain_resource_name": parent.metadata.name,
        "namespace": parent.metadata.namespace,
        "platform_resource_name": parent.metadata.labels["konfig.realkinetic.com/platform"],
        "domain_human_name": has(parent.spec.domainName) ? parent.spec.domainName: parent.metadata.name
      }
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: domain-subresource-metadata.v1
  namespace: koreo-testing
spec:
  behavior:
    load: virtual
    create: false
    update: never
    delete: abandon

  outcome:
    okValue: |
      ={
        "name": inputs.config.domain_resource_name,
        "namespace": inputs.config.namespace,
        "labels": {
          "app.kubernetes.io/managed-by": "konfig",
          "konfig.realkinetic.com/platform": inputs.config.platform_resource_name,
          "konfig.realkinetic.com/domain": inputs.config.domain_resource_name,
          "konfig-platform": inputs.config.platform_resource_name,
          "konfig-domain": inputs.config.domain_resource_name,
          "testing": string("is fun!")
        }
      }
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: domain-subresource-value.v1
  namespace: koreo-testing
spec:
  behavior:
    load: virtual
    create: false
    update: never
    delete: abandon

  inputValidators:
    - type: PermFail
      message: testing skip encoding
      test: "=!has(inputs.metadata.name)"

  outcome:
    okValue: |
      ={
        "metadata-name": inputs.metadata.name,
        "config-human-name": inputs.config.domain_human_name
      }
