apiVersion: v1
kind: Namespace
metadata:
  name: koreo-testing
---
apiVersion: konfig.realkinetic.com/v1alpha8
kind: Domain
metadata:
  name: fully-built-trigger
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/bumper: "1"
spec:
  domainName: Testing
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Workflow
metadata:
  name: fully-built.v1
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/bump: "2"
spec:
  crdRef:
    apiGroup: konfig.realkinetic.com
    version: v1alpha8
    kind: Domain

  steps:
    - label: empty
      functionRef:
        name: empty.v1
    - label: ok-value
      functionRef:
        name: outcome-ok-value.v1
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Workflow
metadata:
  name: flojo-mojo.v1
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/bump: "1"
spec:
  crdRef:
    apiGroup: konfig.realkinetic.com
    version: v1alpha8
    kind: Domain

  steps:
    - label: config
      functionRef:
        name: domain-config.v1
    - label: metadata
      functionRef:
        name: domain-subresource-metadata.v1
      inputs:
        config: steps.config
      staticInputs:
        test_label: test label value
    - label: value
      functionRef:
        name: domain-subresource-value.v1
      inputs:
        config: steps.config
        metadata: steps.metadata
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Workflow
metadata:
  name: fully-built-2.v1
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/bump: "2"
spec:
  crdRef:
    apiGroup: konfig.realkinetic.com
    version: v1alpha8
    kind: Domain

  steps:
    - label: empty
      functionRef:
        name: empty.v1
    - label: ok-value
      functionRef:
        name: outcome-ok-value.v1
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Workflow
metadata:
  name: dummy-test-1.v1
  namespace: koreo-testing
spec:
  crdRef:
    apiGroup: konfig.realkinetic.com
    version: v1alpha8
    kind: Domain

  steps:
    - label: ok-value
      functionRef:
        name: dummy-test.v1
