apiVersion: v1
kind: Namespace
metadata:
  name: koreo-testing
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: empty
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: empty
    koreo.realkinetic.com/version: v1
    koreo.realkinetic.com/bump: "13"
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: input-validation-tests
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: input-validation-tests
    koreo.realkinetic.com/version: v1
spec:
  inputValidators:
    - type: Skip
      message: number too small, must be over 5.
      test: inputs.number < 5

    - type: PermFail
      message: optional number not equal to 3333.
      test: has(inputs.optional_number) && inputs.optional_number != 3333

    - type: Retry
      message: number too large, must be under 13.
      test: inputs.number > 13
      delay: 90

    - type: PermFail
      message: number too small, must be over 1.
      test: inputs.number < 1

    - type: Retry
      message: optional retry_number not equal to 1212.
      test: has(inputs.optional_retry_number) && inputs.optional_retry_number != 1212
      delay: 75
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: outcome-tests
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: outcome-tests
    koreo.realkinetic.com/version: v1
spec:
  outcome:
    tests:
      - type: Retry
        message: number too large, must be under 13.
        test: inputs.number > 13
        delay: 90

      - type: PermFail
        message: optional number not equal to 3333.
        test: has(inputs.optional_number) && inputs.optional_number != 3333

      - type: Ok
        test: has(inputs.output) && inputs.output == 11221122
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: outcome-ok-value
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: outcome-ok-value
    koreo.realkinetic.com/version: v1
    koreo.realkinetic.com/bump: "4"
spec:
  outcome:
    okValue: "has(inputs.output) ? inputs.output: null"
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: materializers-base-nested
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: materializers-base-nested
    koreo.realkinetic.com/version: v1
    koreo.realkinetic.com/bump: "12"
spec:
  materializers:
    base:
      metadata:
        namespace: inputs.metadata.namespace
      spec:
        name: inputs.person.name
        age: inputs.person.age
        children.*: |
          { "name": inputs.person.name + ", Jr.", "age": inputs.person.age - 20 }

  template:
    apiVersion: tests.koreo.realkinetic.com/v1alpha8
    kind: TestCase
    metadata:
      name: base-test
    spec:
      name: Name of Person
      age: Age of Person
      children:
        - name: Name of Child
          age: Age of Child
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: materializers-base-flat
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: materializers-base-flat
    koreo.realkinetic.com/version: v1
spec:
  materializers:
    base:
      "metadata.namespace": inputs.metadata.namespace
      "spec.name": inputs.person.name
      "spec.age": inputs.person.age
      "spec.children.*": |
        { "name": inputs.person.name + ", Jr.", "age": inputs.person.age - 20 }

  template:
    apiVersion: tests.koreo.realkinetic.com/v1alpha8
    kind: TestCase
    metadata:
      name: base-test
    spec:
      name: Name of Person
      age: Age of Person
      children:
        - name: Name of Child
          age: Age of Child
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: materializers-on-create-nested
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: materializers-on-create-nested
    koreo.realkinetic.com/version: v1
spec:
  materializers:
    onCreate:
      metadata:
        namespace: inputs.metadata.namespace
      spec:
        name: inputs.person.name
        age: inputs.person.age
        children.*: |
          { "name": inputs.person.name + ", Jr.", "age": inputs.person.age - 20 }

  template:
    apiVersion: tests.koreo.realkinetic.com/v1alpha8
    kind: TestCase
    metadata:
      name: base-test
    spec:
      name: Name of Person
      age: Age of Person
      children:
        - name: Name of Child
          age: Age of Child
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: materializers-on-create-flat
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: materializers-on-create-flat
    koreo.realkinetic.com/version: v1
spec:
  materializers:
    onCreate:
      "metadata.namespace": inputs.metadata.namespace
      "spec.name": inputs.person.name
      "spec.age": inputs.person.age
      "spec.children.*": |
        { "name": inputs.person.name + ", Jr.", "age": inputs.person.age - 20 }

  template:
    apiVersion: tests.koreo.realkinetic.com/v1alpha8
    kind: TestCase
    metadata:
      name: base-test
    spec:
      name: Name of Person
      age: Age of Person
      children:
        - name: Name of Child
          age: Age of Child
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: gcp-folder.v1
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: gcp-folder
    koreo.realkinetic.com/version: v1
spec:
  outcome:
    tests:
      - type: Ok
        test: resource.config_connect_ready()

    okValue: |
      {"folderId": resource.status.folderId, "ref": resource.self_ref() }

  materializers:
    base:
      metadata: inputs.metadata
      spec:
        displayName: inputs.params.name
        folderRef: inputs.parent_folder.ref.to_ref()

  template:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Folder
---
apiVersion: koreo.realkinetic.com/v1alpha8
kind: Function
metadata:
  name: dummy-test
  namespace: koreo-testing
  labels:
    koreo.realkinetic.com/name: dummy-test
    koreo.realkinetic.com/version: v1
spec:
  managedResource:
    crd:
      apiVersion: koreo.realkinetic.com/v1alpha8
      kind: TestDummy
      plural: testdummies
      namespaced: true
    behaviors:
      update: recreate

  materializers:
    base:
      "metadata.name": parent.metadata.name
      "metadata.namespace": string("koreo-testing")
      spec:
        intKey: 99
        strKey: string("A string!")

  template:
    apiVersion: koreo.realkinetic.com/v1alpha8
    kind: TestDummy
    metadata:
      labels:
        testing.realkinetic.com/key: value
    spec:
      intKey: 7
      strKey: "yay"
      listKey:
        - name: first
          value: 1
        - name: second
          value: 2
      mapKey:
        name: some
        value: 1
