apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: Workflow
    plural: workflows
    singular: workflow
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                crdRef:
                  nullable: false
                  type: object
                  properties:
                    apiGroup:
                      type: string
                      nullable: false
                    version:
                      type: string
                      nullable: false
                    kind:
                      type: string
                      nullable: false
                  required: [apiGroup, version, kind]
                steps:
                  nullable: true
                  type: array
                  maxItems: 20
                  items:
                    type: object
                    properties:
                      label:
                        type: string
                        nullable: false
                        maxLength: 40
                        x-kubernetes-validations:
                          - rule: self.matches("^[[:word:]]+$")
                            message: "step labels must be alphanumeric (underscore is ok)."
                      functionRef:
                        type: object
                        nullable: false
                        properties:
                          name:
                            type: string
                            nullable: false
                        required: [name]
                      mappedInput:
                        type: object
                        nullable: true
                        properties:
                          source:
                            type: string
                            nullable: false
                          inputKey:
                            type: string
                            nullable: false
                      inputs:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        nullable: true
                    required: [label, functionRef]
                status:
                  type: object
                  nullable: true
                  properties:
                    conditions:
                      nullable: true
                      type: array
                      maxItems: 20
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                            nullable: false
                            maxLength: 40
                            x-kubernetes-validations:
                              - rule: self.matches("^[A-Z][a-zA-Z0-9]+$")
                                message: "type must be CamelCase, and contain only alphanumeric chars"
                          name:
                            type: string
                            nullable: false
                            maxLength: 40
                            x-kubernetes-validations:
                              - rule: "!self.startsWith('=')"
                                message: "name may not be a CEL expression."
                          step:
                            type: string
                            nullable: true
                            maxLength: 40
                            x-kubernetes-validations:
                              - rule: self.matches("^[[:word:]]+$")
                                message: "step labels must be alphanumeric (underscore is ok)."
                        required: [type, name, step]
                    state:
                      type: object
                      nullable: true
                      maxProperties: 50
                      additionalProperties:
                        type: string
              x-kubernetes-validations:
                - rule: |
                    !has(self.status) ||
                    !has(self.status.conditions) ||
                    self.status.conditions.all(
                      condition,
                      size(self.steps.filter(step, step.label == condition.step)) == 1
                    )
                  message: "conditions step must exist as steps label"
              required: [crdRef, steps]
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
