apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: Workflow
    plural: workflows
    singular: workflow
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              nullable: false
              properties:
                crdRef:
                  nullable: false
                  type: object
                  properties:
                    apiGroup:
                      type: string
                      nullable: false
                    version:
                      type: string
                      nullable: false
                    kind:
                      type: string
                      nullable: false
                  required: [apiGroup, version, kind]
                configStep:
                  nullable: false
                  type: object
                  properties:
                    label:
                      type: string
                      nullable: false
                      default: config
                      maxLength: 40
                      x-kubernetes-validations:
                        - rule: self.matches("^[[:word:]]+$")
                          message: "step labels must be alphanumeric (underscore is ok)."
                    functionRef:
                      type: object
                      nullable: false
                      properties:
                        kind:
                          type: string
                          nullable: false
                          enum: [ResourceFunction, ValueFunction, Function]
                        name:
                          type: string
                          nullable: false
                      required: [kind, name]
                    workflowRef:
                      type: object
                      nullable: false
                      properties:
                        name:
                          type: string
                          nullable: false
                      required: [name]
                    inputs:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                      nullable: false
                    condition:
                      nullable: false
                      type: object
                      properties:
                        type:
                          type: string
                          nullable: false
                          maxLength: 40
                          x-kubernetes-validations:
                            - rule: self.matches("^[A-Z][a-zA-Z0-9]+$")
                              message: "type must be CamelCase, and contain only alphanumeric chars"
                        name:
                          type: string
                          nullable: false
                          maxLength: 60
                          x-kubernetes-validations:
                            - rule: "!self.startsWith('=')"
                              message: "name may not be a CEL expression."
                  oneOf:
                    - required: [functionRef]
                    - required: [workflowRef]
                steps:
                  nullable: false
                  type: array
                  maxItems: 20
                  items:
                    type: object
                    properties:
                      label:
                        type: string
                        nullable: false
                        maxLength: 40
                        x-kubernetes-validations:
                          - rule: self.matches("^[[:word:]]+$")
                            message: "step labels must be alphanumeric (underscore is ok)."
                      functionRef:
                        type: object
                        nullable: false
                        properties:
                          kind:
                            type: string
                            nullable: false
                            enum: [ResourceFunction, ValueFunction, Function]
                          name:
                            type: string
                            nullable: false
                        required: [kind, name]
                      workflowRef:
                        type: object
                        nullable: false
                        properties:
                          name:
                            type: string
                            nullable: false
                        required: [name]
                      forEach:
                        type: object
                        nullable: false
                        properties:
                          itemIn:
                            type: string
                            nullable: false
                          inputKey:
                            type: string
                            nullable: false
                        required: [itemIn, inputKey]
                      inputs:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        nullable: false
                      condition:
                        nullable: false
                        type: object
                        properties:
                          type:
                            type: string
                            nullable: false
                            maxLength: 40
                            x-kubernetes-validations:
                              - rule: self.matches("^[A-Z][a-zA-Z0-9]+$")
                                message: "type must be CamelCase, and contain only alphanumeric chars"
                          name:
                            type: string
                            nullable: false
                            maxLength: 60
                            x-kubernetes-validations:
                              - rule: "!self.startsWith('=')"
                                message: "name may not be a CEL expression."
                        required: [type, name]
                    required: [label]
                    oneOf:
                      - required: [functionRef]
                      - required: [workflowRef]
                status:
                  type: object
                  nullable: false
                  properties:
                    conditions:
                      nullable: false
                      type: array
                      maxItems: 20
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                            nullable: false
                            maxLength: 40
                            x-kubernetes-validations:
                              - rule: self.matches("^[A-Z][a-zA-Z0-9]+$")
                                message: "type must be CamelCase, and contain only alphanumeric chars"
                          name:
                            type: string
                            nullable: false
                            maxLength: 60
                            x-kubernetes-validations:
                              - rule: "!self.startsWith('=')"
                                message: "name may not be a CEL expression."
                          step:
                            type: string
                            nullable: false
                            maxLength: 40
                            x-kubernetes-validations:
                              - rule: self.matches("^[[:word:]]+$")
                                message: "step labels must be alphanumeric (underscore is ok)."
                        required: [type, name, step]
                    state:
                      type: object
                      nullable: false
                      maxProperties: 50
              x-kubernetes-validations:
                - rule: |
                    !has(self.status) ||
                    !has(self.status.conditions) ||
                    self.status.conditions.all(
                      condition,
                      size(self.steps.filter(step, step.label == condition.step)) == 1
                    )
                  message: "conditions step must exist as steps label"
              required: [crdRef, steps]
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
