apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: workflows.koreo.realkinetic.com
spec:
  scope: Namespaced
  group: koreo.realkinetic.com
  names:
    kind: Workflow
    plural: workflows
    singular: workflow
  versions:
    - name: v1alpha8
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                crdRef:
                  nullable: false
                  type: object
                  properties:
                    apiGroup:
                      type: string
                      nullable: false
                    version:
                      type: string
                      nullable: false
                    kind:
                      type: string
                      nullable: false
                  required: [apiGroup, version, kind]
                steps:
                  nullable: true
                  type: array
                  maxItems: 20
                  items:
                    type: object
                    properties:
                      label:
                        type: string
                        nullable: false
                        x-kubernetes-validations:
                          - rule: "!self.contains('.')"
                            message: "step labels may not '.'"
                      functionRef:
                        type: object
                        nullable: false
                        properties:
                          name:
                            type: string
                            nullable: false
                        required: [name]
                      inputs:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        nullable: true
                      staticInputs:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                        nullable: true
                    required: [label, functionRef]
                outcome:
                  nullable: true
                  type: object
                  properties:
                    tests:
                      nullable: true
                      type: array
                      maxItems: 20
                      items:
                        type: object
                        x-kubernetes-validations:
                          - rule: (self.type == 'Retry' && has(self.delay) && self.delay > 0) || self.type != 'Retry'
                            message: "Retry validators must provide delay-seconds."
                          - rule: (self.type != 'Retry' && !has(self.delay)) || self.type == 'Retry'
                            message: "Non-retry validators must not provide delay-seconds."
                          - rule: (self.type == 'Ok' && !has(self.message)) || self.type != 'Ok'
                            message: "Ok validators should not provide a message."

                        properties:
                          type:
                            type: string
                            nullable: false
                            enum: [Ok, PermFail, Retry]
                          test:
                            type: string
                            nullable: false
                            x-kubernetes-validations:
                              - rule: self.startsWith('=')
                                message: "test must be a cel expression."
                          message:
                            type: string
                            nullable: true
                          delay:
                            type: integer
                            nullable: true
                        required: [type, test]
                    okValue:
                      nullable: true
                      type: string
              required: [crdRef, steps]
            status:
              x-kubernetes-preserve-unknown-fields: true
              type: object
