name: PDM Build, Test, and Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.13"
          cache: true

      - name: Install dependencies
        run: pdm install --dev

      - name: Run tests
        run: pdm run pytest

  publish:
    name: Publish to PyPI
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install PDM
        run: pipx install pdm

      - name: Build package
        run: pdm build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: pdm publish --username __token__ --password "$PYPI_TOKEN"
